[tool.poetry]
name = "dougslldataplatform"
version = "0.1.0"
description = ""
authors = ["Leal <douglas.sleal@outlook.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
